name: 'tauri-action'
description: 'action to build and distribute tauri apps'
author: 'H3rmt'
inputs:
  releaseId:
    description: 'The id of the release to upload artifacts as release assets'
  version:
    description: 'string with sem. version from tauri.conf.json'  
  path: 
    description: 'path to folder with tauri project'
  name:
    description: 'name of project'

outputs:
  sigs:
    description: 'sign of this build'

runs:
  using: 'node16'
  main: 'dist/index.js'
