name: 'tauri-action'
description: 'action to build and distribute tauri apps'
author: 'H3rmt'
inputs:
  releaseId:
    description: 'The id of the release to upload artifacts as release assets'

runs:
  using: 'node16'
  main: 'dist/index.js'
